import type { Meta, StoryObj } from '@storybook/angular';
import { PosProductCardListComponent } from './pos-product-card-list.component';

import { within } from '@storybook/testing-library';
import { expect } from '@storybook/jest';

const meta: Meta<PosProductCardListComponent> = {
  component: PosProductCardListComponent,
  title: 'PosProductCardListComponent',
};
export default meta;
type Story = StoryObj<PosProductCardListComponent>;

export const Primary: Story = {
  args: {},
};

export const Heading: Story = {
  args: {
    productListItems: [
      {
        id: 1,
        barcode: '100000000011',
        name: 'PRODUCT_1_SKU_1',
        price: 100.0,
        cost: 100.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 10,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 1,
        productUpc: '100000000001',
      },
      {
        id: 2,
        barcode: '100000000012',
        name: 'PRODUCT_1_SKU_2',
        price: 400.0,
        cost: 400.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 40,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 1,
        productUpc: '100000000001',
      },
      {
        id: 3,
        barcode: '100000000013',
        name: 'PRODUCT_1_SKU_3',
        price: 700.0,
        cost: 700.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 70,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 1,
        productUpc: '100000000001',
      },
      {
        id: 4,
        barcode: '100000000024',
        name: 'PRODUCT_2_SKU_4',
        price: 1000.0,
        cost: 1000.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 100,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 2,
        productUpc: '100000000002',
      },
      {
        id: 5,
        barcode: '100000000025',
        name: 'PRODUCT_2_SKU_5',
        price: 1300.0,
        cost: 1300.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 130,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 2,
        productUpc: '100000000002',
      },
      {
        id: 6,
        barcode: '100000000026',
        name: 'PRODUCT_2_SKU_6',
        price: 1600.0,
        cost: 1600.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 160,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 2,
        productUpc: '100000000002',
      },
      {
        id: 7,
        barcode: '100000000037',
        name: 'PRODUCT_3_SKU_7',
        price: 1900.0,
        cost: 1900.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 190,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 3,
        productUpc: '100000000003',
      },
      {
        id: 8,
        barcode: '100000000038',
        name: 'PRODUCT_3_SKU_8',
        price: 2200.0,
        cost: 2200.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 220,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 3,
        productUpc: '100000000003',
      },
      {
        id: 9,
        barcode: '100000000039',
        name: 'PRODUCT_3_SKU_9',
        price: 2500.0,
        cost: 2500.0,
        priceLevelId: 1,
        priceLevelName: 'PL_1',
        storeId: 1,
        quantity: 250,
        storeName: 'STORE_1',
        category: 'Default Category',
        department: 'Default Department',
        productId: 3,
        productUpc: '100000000003',
      },
    ],
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText(/pos-product-card-list works!/gi)).toBeTruthy();
  },
};
